apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-greeting-web-deployment
  labels:
    app: app1-greeting-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-greeting-web
  template:
    metadata:
      labels:
        app: app1-greeting-web
    spec:
      containers:
        - name: app1-greeting-web
          image: aparnacontainer11.azurecr.io/greeting-web
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-greeting-web-loadbalancer-service
  labels:
    app: app1-greeting-web
spec:
  type: LoadBalancer
  selector:
    app: app1-greeting-web
  ports:
    - port: 80
      targetPort: 80